### PR TITLE
Delete `interface.tsx` and define component in `index.tsx` in `<Textfield />`

### PR DESCRIPTION
**Pull request by Andresbl123**
The `interface.tsx` component, which corresponded to the layout part of the component, is removed and integrated into `index.tsx`, keeping the layout and logical operations part in the same file.

### CODE REVIEW

**Comment by Andresbl123** [comment]
Reseulto

**Review by cmarin001 — COMMENTED** [review]
aun no esta correctamente integrado con lo que hay en main

**Comment by Andresbl123** [comment]
Resuelto

**Review by cmarin001 — APPROVED** [review]
cumple con los requerimientos

**Pull request merged**
